### ISSUE TITLE
Graphen faerbung

### ISSUE THREAD

**Issue by MarkusKral** [ob-algdatii-ss18/leistungsnachweis-hornet#1]
Es soll zu einem gegebenen Graphen und einer gegebenen Anzahl an Farben ermittelt werden, ob und wie dieser Graph mittels der gegebenen Farben so gefaerbt werden kann, das kein Knoten die selbe Farbe besitzt wie einer seiner Nachbarn.

Dieser Graph soll mittels graphviz visualisiert werden.

**Comment by obcode** [comment]
Arbeiten Sie alleine?

**Comment by MarkusKral** [comment]
Nein, wir sind zu zweit, mein Gruppenpartner schreibt sich erst noch in die Gruppe ein.
